services:
  openbao:
    image: ghcr.io/openbao/openbao:2.6.1
    container_name: openbao
    hostname: openbao
    user: "0:0"
    restart: unless-stopped

    command:
      - server
      - -config=/openbao/config/openbao.hcl

    ports:
      - "127.0.0.1:8200:8200"

    volumes:
      - ./config:/openbao/config:ro
      - ./data:/openbao/data
      - ./audit:/openbao/audit
      - ./logs:/openbao/logs

    networks:
      - jason-core

    environment:
      BAO_ADDR: http://127.0.0.1:8200

    cap_add:
      - IPC_LOCK

    security_opt:
      - no-new-privileges:true

    mem_swappiness: 0

networks:
  jason-core:
    external: true
    name: jason-core
