#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
IMPLEMENTATION = REPO_ROOT / "implementation"
if str(IMPLEMENTATION) not in sys.path:
    sys.path.insert(0, str(IMPLEMENTATION))

from kernel.system_registry.contracts import EntityLifecycle  # noqa: E402
from kernel.system_registry.manifest import registry_from_manifest  # noqa: E402


DEFAULT_MANIFEST = REPO_ROOT / "implementation/kernel/system_registry/production-registry.json"
DEFAULT_LIFECYCLE_EVENTS = REPO_ROOT / "implementation/kernel/system_registry/production-lifecycle-events.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs/operations/System-Registry-Current-Operational-State.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Jason operational-state documentation from governed System Registry truth."
    )
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--lifecycle-events", type=Path, default=DEFAULT_LIFECYCLE_EVENTS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed generated document differs from current registry truth.",
    )
    return parser.parse_args()


def _current_repo_evidence_reference(reference: str) -> str | None:
    """Map immutable historical repository evidence references to their current path.

    Lifecycle events remain append-only evidence and are not rewritten merely because
    the documentation control plane moved. The generated human view resolves the old
    repository location to the current canonical session-record location.
    """

    legacy_prefix = "08-Session-Records/"
    current_prefix = "docs/sessions/"
    if reference.startswith(legacy_prefix):
        candidate = current_prefix + reference.removeprefix(legacy_prefix)
        if (REPO_ROOT / candidate).is_file():
            return candidate
        return reference
    if reference.startswith(current_prefix):
        return reference
    return None


def render(manifest: Path, lifecycle_events: Path) -> str:
    registry = registry_from_manifest(
        manifest,
        lifecycle_events_path=lifecycle_events,
    )
    entities = registry.list_all()
    lifecycle_counts = Counter(entity.lifecycle_status.value for entity in entities)
    environments = ", ".join(sorted({entity.environment for entity in entities}))

    lines = [
        "# Jason System Registry — Current Operational State",
        "",
        "> Generated from governed System Registry structured truth. Do not edit this file directly.",
        "",
        "## Source of truth",
        "",
        "- Baseline registry: `implementation/kernel/system_registry/production-registry.json`",
        "- Lifecycle history: `implementation/kernel/system_registry/production-lifecycle-events.json`",
        "- Environment(s): `" + environments + "`",
        f"- Registered entities: `{len(entities)}`",
        "- Effective lifecycle counts: `"
        + ", ".join(f"{key}={lifecycle_counts[key]}" for key in sorted(lifecycle_counts))
        + "`",
        "",
        "## Verified current physical topology",
        "",
        "| Registry ID | Type | Verification method | Governed evidence record |",
        "|---|---|---|---|",
    ]

    verified = [
        entity for entity in entities if entity.lifecycle_status is EntityLifecycle.VERIFIED
    ]
    for entity in verified:
        verification = registry.latest_verification(entity.registry_id)
        if verification is None:
            raise RuntimeError(f"Verified entity lacks verification record: {entity.registry_id}")
        repo_evidence = [
            current
            for reference in verification.evidence_references
            if (current := _current_repo_evidence_reference(reference)) is not None
        ]
        rendered_evidence = "<br>".join(f"`{item}`" for item in repo_evidence) or "—"
        lines.append(
            f"| `{entity.registry_id}` | `{entity.entity_type.value}` | "
            f"`{verification.method}` | {rendered_evidence} |"
        )

    lines.extend(
        [
            "",
            "## Registered but not yet verified",
            "",
            "| Registry ID | Type | Lifecycle | Required verification method(s) |",
            "|---|---|---|---|",
        ]
    )

    for entity in entities:
        if entity.lifecycle_status is EntityLifecycle.VERIFIED:
            continue
        methods = ", ".join(f"`{method}`" for method in entity.verification_methods) or "—"
        lines.append(
            f"| `{entity.registry_id}` | `{entity.entity_type.value}` | "
            f"`{entity.lifecycle_status.value}` | {methods} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation boundary",
            "",
            "`verified` means the entity has governed evidence satisfying its registered verification method and lifecycle transition. It does not mean `active`, and it does not prove unrelated providers, identities, capabilities, governance gates, or deployments.",
            "",
            "Logical records remain unpromoted until their own registered verification methods are satisfied. A healthy physical topology does not by itself prove Datto RMM authorization, Microsoft Graph identity resolution, AWS SES delivery authority, capability execution, or full deployment readiness.",
            "",
            "The lifecycle event history is append-only operational evidence. Baseline declared state remains separate from the effective lifecycle derived from governed events.",
            "",
            "Historical lifecycle-event repository paths are preserved in the append-only event source. This generated view resolves those references to the current `docs/sessions/` location when the migrated evidence record exists.",
            "",
            "## Regeneration",
            "",
            "Run `python tools/system_registry_docs.py` after an approved registry, lifecycle-event, or documentation-path change. CI runs `python tools/system_registry_docs.py --check` and fails if this generated view is stale.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    rendered = render(args.manifest, args.lifecycle_events)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            print(
                "Generated System Registry operational-state documentation is stale. "
                "Run: python tools/system_registry_docs.py",
                file=sys.stderr,
            )
            return 2
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(str(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
