"""Provider-neutral deterministic query execution over verified governed records.

The query engine knows nothing about providers, connectors, API routes, credentials,
human phrases, endpoint-specific facts, or business workflows.

Upstream planning supplies a validated query plan and verified records. This module
only performs deterministic relational operations over those records.

Supported generic operations:
- source selection
- inner/left equality joins
- field/literal/relative-time expressions
- boolean predicates
- comparison
- projection
- grouping
- aggregation
- ordering
- limit

Operational values are never generated by a model here.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from typing import Any, Mapping, Sequence


_ALLOWED_COMPARISONS = frozenset({
    "eq",
    "ne",
    "lt",
    "lte",
    "gt",
    "gte",
})

_ALLOWED_AGGREGATES = frozenset({
    "count",
    "count_distinct",
    "sum",
    "min",
    "max",
    "avg",
})

_ALLOWED_JOIN_TYPES = frozenset({
    "inner",
    "left",
})

_ALLOWED_DIRECTIONS = frozenset({
    "asc",
    "desc",
})

_MAX_SOURCES = 16
_MAX_RECORDS_PER_SOURCE = 100000
_MAX_JOINS = 16
_MAX_FILTERS = 64
_MAX_PROJECTIONS = 64
_MAX_GROUP_FIELDS = 16
_MAX_AGGREGATES = 32
_MAX_ORDER_FIELDS = 16
_MAX_LIMIT = 10000


class GovernedQueryError(ValueError):
    """A query plan or deterministic execution request was invalid."""


@dataclass(frozen=True, slots=True)
class VerifiedQueryRecord:
    """One already-verified provider-neutral resource observation."""

    entity_id: str
    resource_type: str
    facts: Mapping[str, Any]
    evidence_references: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.entity_id.strip():
            raise ValueError("verified query record entity_id is required")
        if not self.resource_type.strip():
            raise ValueError("verified query record resource_type is required")
        if any(not str(key).strip() for key in self.facts):
            raise ValueError("verified query fact names must be non-empty")
        if any(not str(item).strip() for item in self.evidence_references):
            raise ValueError("evidence references must be non-empty")


@dataclass(frozen=True, slots=True)
class VerifiedQueryDataset:
    """Verified records made available under one provider-neutral query alias."""

    alias: str
    resource_type: str
    records: tuple[VerifiedQueryRecord, ...]

    def __post_init__(self) -> None:
        if not self.alias.strip():
            raise ValueError("query dataset alias is required")
        if not self.resource_type.strip():
            raise ValueError("query dataset resource_type is required")
        if len(self.records) > _MAX_RECORDS_PER_SOURCE:
            raise ValueError("query dataset exceeds bounded record count")
        for record in self.records:
            if record.resource_type != self.resource_type:
                raise ValueError(
                    "query dataset contains a mismatched resource type"
                )


@dataclass(frozen=True, slots=True)
class QueryField:
    source: str
    fact: str

    def __post_init__(self) -> None:
        if not self.source.strip():
            raise ValueError("query field source is required")
        if not self.fact.strip():
            raise ValueError("query field fact is required")


@dataclass(frozen=True, slots=True)
class QueryLiteral:
    value: Any


@dataclass(frozen=True, slots=True)
class QueryRelativeTime:
    """A deterministic UTC instant relative to execution time."""

    amount: int
    unit: str
    direction: str = "past"

    def __post_init__(self) -> None:
        if self.amount < 0:
            raise ValueError("relative time amount must not be negative")
        if self.unit not in {"minutes", "hours", "days", "weeks"}:
            raise ValueError("relative time unit is invalid")
        if self.direction not in {"past", "future"}:
            raise ValueError("relative time direction is invalid")


@dataclass(frozen=True, slots=True)
class QueryOutput:
    """Reference one named value produced by projection/grouping/aggregation."""

    name: str

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise ValueError("query output name is required")


QueryExpression = QueryField | QueryLiteral | QueryRelativeTime | QueryOutput


@dataclass(frozen=True, slots=True)
class QueryPredicate:
    left: QueryExpression
    operator: str
    right: QueryExpression

    def __post_init__(self) -> None:
        if self.operator not in _ALLOWED_COMPARISONS:
            raise ValueError("query comparison operator is invalid")


@dataclass(frozen=True, slots=True)
class QueryJoin:
    left: QueryField
    right: QueryField
    join_type: str = "inner"

    def __post_init__(self) -> None:
        if self.join_type not in _ALLOWED_JOIN_TYPES:
            raise ValueError("query join type is invalid")
        if self.left.source == self.right.source:
            raise ValueError("query join must connect different sources")


@dataclass(frozen=True, slots=True)
class QueryProjection:
    name: str
    expression: QueryExpression

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise ValueError("query projection name is required")


@dataclass(frozen=True, slots=True)
class QueryAggregate:
    name: str
    operation: str
    expression: QueryExpression | None = None

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise ValueError("query aggregate name is required")
        if self.operation not in _ALLOWED_AGGREGATES:
            raise ValueError("query aggregate operation is invalid")
        if self.operation == "count":
            return
        if self.expression is None:
            raise ValueError(
                "non-count aggregate requires an expression"
            )


@dataclass(frozen=True, slots=True)
class QueryOrder:
    expression: QueryExpression
    direction: str = "asc"

    def __post_init__(self) -> None:
        if self.direction not in _ALLOWED_DIRECTIONS:
            raise ValueError("query order direction is invalid")


@dataclass(frozen=True, slots=True)
class GovernedQueryPlan:
    """Validated provider-neutral relational plan."""

    sources: tuple[str, ...]
    joins: tuple[QueryJoin, ...] = ()
    filters: tuple[QueryPredicate, ...] = ()
    projections: tuple[QueryProjection, ...] = ()
    group_by: tuple[QueryProjection, ...] = ()
    aggregates: tuple[QueryAggregate, ...] = ()
    order_by: tuple[QueryOrder, ...] = ()
    limit: int | None = None

    def __post_init__(self) -> None:
        clean_sources = tuple(
            item.strip()
            for item in self.sources
            if item.strip()
        )
        if not clean_sources:
            raise ValueError("query plan requires at least one source")
        if len(clean_sources) != len(set(clean_sources)):
            raise ValueError("query plan source aliases must be unique")
        if len(clean_sources) > _MAX_SOURCES:
            raise ValueError("query plan exceeds source bound")
        if len(self.joins) > _MAX_JOINS:
            raise ValueError("query plan exceeds join bound")
        if len(self.filters) > _MAX_FILTERS:
            raise ValueError("query plan exceeds filter bound")
        if len(self.projections) > _MAX_PROJECTIONS:
            raise ValueError("query plan exceeds projection bound")
        if len(self.group_by) > _MAX_GROUP_FIELDS:
            raise ValueError("query plan exceeds group bound")
        if len(self.aggregates) > _MAX_AGGREGATES:
            raise ValueError("query plan exceeds aggregate bound")
        if len(self.order_by) > _MAX_ORDER_FIELDS:
            raise ValueError("query plan exceeds ordering bound")
        if self.limit is not None:
            if self.limit < 1 or self.limit > _MAX_LIMIT:
                raise ValueError("query plan limit is outside safety bound")
        if self.group_by and not self.aggregates:
            raise ValueError("group_by requires at least one aggregate")


@dataclass(frozen=True, slots=True)
class GovernedQueryResult:
    columns: tuple[str, ...]
    rows: tuple[Mapping[str, Any], ...]
    source_aliases: tuple[str, ...]
    evidence_references: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class DeterministicGovernedQueryEngine:
    """Execute a validated query plan over verified records only."""

    def execute(
        self,
        *,
        plan: GovernedQueryPlan,
        datasets: Sequence[VerifiedQueryDataset],
        now: datetime | None = None,
    ) -> GovernedQueryResult:
        source_map = {
            item.alias: item
            for item in datasets
        }

        if len(source_map) != len(tuple(datasets)):
            raise GovernedQueryError(
                "query datasets contain duplicate aliases"
            )

        unknown = set(plan.sources).difference(source_map)
        if unknown:
            raise GovernedQueryError(
                "query plan references unavailable source aliases: "
                + ", ".join(sorted(unknown))
            )

        execution_now = (
            now.astimezone(timezone.utc)
            if now is not None
            else datetime.now(timezone.utc)
        )

        rows = self._initial_rows(
            source_map[plan.sources[0]]
        )

        joined_sources = {
            plan.sources[0]
        }

        remaining_joins = list(
            plan.joins
        )

        while remaining_joins:
            progressed = False

            for join in tuple(
                remaining_joins
            ):
                left_known = (
                    join.left.source
                    in joined_sources
                )
                right_known = (
                    join.right.source
                    in joined_sources
                )

                if left_known == right_known:
                    continue

                if left_known:
                    incoming_alias = (
                        join.right.source
                    )
                    existing_field = (
                        join.left
                    )
                    incoming_field = (
                        join.right
                    )
                else:
                    incoming_alias = (
                        join.left.source
                    )
                    existing_field = (
                        join.right
                    )
                    incoming_field = (
                        join.left
                    )

                if (
                    incoming_alias
                    not in plan.sources
                ):
                    raise GovernedQueryError(
                        "join references a source "
                        "outside the query plan"
                    )

                rows = self._join(
                    rows=rows,
                    dataset=source_map[
                        incoming_alias
                    ],
                    existing_field=(
                        existing_field
                    ),
                    incoming_field=(
                        incoming_field
                    ),
                    join_type=join.join_type,
                    now=execution_now,
                )

                joined_sources.add(
                    incoming_alias
                )
                remaining_joins.remove(
                    join
                )
                progressed = True

            if not progressed:
                raise GovernedQueryError(
                    "query joins do not form a connected "
                    "acyclic execution path"
                )

        for source in plan.sources:
            if source not in joined_sources:
                raise GovernedQueryError(
                    "multiple query sources require "
                    "explicit governed joins"
                )

        for predicate in plan.filters:
            rows = [
                row
                for row in rows
                if _evaluate_predicate(
                    predicate,
                    row=row,
                    now=execution_now,
                )
            ]

        if plan.aggregates:
            output_rows = _aggregate_rows(
                rows=rows,
                group_by=plan.group_by,
                aggregates=plan.aggregates,
                now=execution_now,
            )
        else:
            projections = (
                plan.projections
                if plan.projections
                else _default_projections(
                    plan.sources
                )
            )

            output_rows = tuple(
                {
                    item.name: _resolve_expression(
                        item.expression,
                        row=row,
                        now=execution_now,
                    )
                    for item in projections
                }
                for row in rows
            )

        if plan.order_by:
            output_rows = _order_rows(
                rows=output_rows,
                order_by=plan.order_by,
                raw_rows=rows,
                now=execution_now,
                aggregate_mode=bool(
                    plan.aggregates
                ),
            )

        if plan.limit is not None:
            output_rows = (
                output_rows[:plan.limit]
            )

        evidence = tuple(
            dict.fromkeys(
                reference
                for row in rows
                for record in row.values()
                if isinstance(
                    record,
                    VerifiedQueryRecord,
                )
                for reference in (
                    record.evidence_references
                )
            )
        )

        columns = (
            tuple(output_rows[0].keys())
            if output_rows
            else _result_columns(plan)
        )

        return GovernedQueryResult(
            columns=columns,
            rows=tuple(output_rows),
            source_aliases=plan.sources,
            evidence_references=evidence,
        )

    @staticmethod
    def _initial_rows(
        dataset: VerifiedQueryDataset,
    ) -> list[
        dict[
            str,
            VerifiedQueryRecord | None,
        ]
    ]:
        return [
            {
                dataset.alias: record,
            }
            for record in dataset.records
        ]

    @staticmethod
    def _join(
        *,
        rows,
        dataset,
        existing_field,
        incoming_field,
        join_type,
        now,
    ):
        result = []

        for row in rows:
            existing_value = (
                _resolve_expression(
                    existing_field,
                    row=row,
                    now=now,
                )
            )

            matches = []

            for record in dataset.records:
                candidate_row = {
                    **row,
                    dataset.alias: record,
                }

                incoming_value = (
                    _resolve_expression(
                        incoming_field,
                        row=candidate_row,
                        now=now,
                    )
                )

                if _compare(
                    existing_value,
                    "eq",
                    incoming_value,
                ):
                    matches.append(
                        candidate_row
                    )

            if matches:
                result.extend(matches)
            elif join_type == "left":
                result.append({
                    **row,
                    dataset.alias: None,
                })

        return result


def _default_projections(
    sources: tuple[str, ...],
) -> tuple[QueryProjection, ...]:
    return tuple(
        QueryProjection(
            name=f"{source}.entity_id",
            expression=QueryField(
                source=source,
                fact="entity_id",
            ),
        )
        for source in sources
    )


def _result_columns(
    plan: GovernedQueryPlan,
) -> tuple[str, ...]:
    if plan.aggregates:
        return tuple(
            item.name
            for item in (
                tuple(plan.group_by)
                + tuple(plan.aggregates)
            )
        )

    if plan.projections:
        return tuple(
            item.name
            for item in plan.projections
        )

    return tuple(
        f"{source}.entity_id"
        for source in plan.sources
    )


def _resolve_expression(
    expression: QueryExpression,
    *,
    row: Mapping[
        str,
        VerifiedQueryRecord | None,
    ],
    now: datetime,
) -> Any:
    if isinstance(
        expression,
        QueryLiteral,
    ):
        return expression.value

    if isinstance(
        expression,
        QueryOutput,
    ):
        raise GovernedQueryError(
            "query output references are only valid after "
            "projection or aggregation"
        )

    if isinstance(
        expression,
        QueryRelativeTime,
    ):
        delta = _relative_delta(
            expression
        )

        return (
            now - delta
            if expression.direction == "past"
            else now + delta
        )

    if not isinstance(
        expression,
        QueryField,
    ):
        raise GovernedQueryError(
            "unknown query expression"
        )

    if expression.source not in row:
        raise GovernedQueryError(
            "query field references "
            "an unavailable source"
        )

    record = row[
        expression.source
    ]

    if record is None:
        return None

    if expression.fact == "entity_id":
        return record.entity_id

    if expression.fact == "resource_type":
        return record.resource_type

    return record.facts.get(
        expression.fact
    )


def _relative_delta(
    value: QueryRelativeTime,
) -> timedelta:
    kwargs = {
        value.unit: value.amount,
    }
    return timedelta(**kwargs)


def _evaluate_predicate(
    predicate: QueryPredicate,
    *,
    row,
    now,
) -> bool:
    left = _resolve_expression(
        predicate.left,
        row=row,
        now=now,
    )
    right = _resolve_expression(
        predicate.right,
        row=row,
        now=now,
    )

    return _compare(
        left,
        predicate.operator,
        right,
    )


def _compare(
    left: Any,
    operator: str,
    right: Any,
) -> bool:
    if operator == "eq":
        return (
            type(left) is type(right)
            and left == right
        )

    if operator == "ne":
        return not _compare(
            left,
            "eq",
            right,
        )

    if left is None or right is None:
        return False

    normalized_left, normalized_right = (
        _comparable_pair(
            left,
            right,
        )
    )

    if operator == "lt":
        return normalized_left < normalized_right
    if operator == "lte":
        return normalized_left <= normalized_right
    if operator == "gt":
        return normalized_left > normalized_right
    if operator == "gte":
        return normalized_left >= normalized_right

    raise GovernedQueryError(
        "unsupported comparison operator"
    )


def _comparable_pair(
    left: Any,
    right: Any,
):
    if (
        isinstance(left, datetime)
        or isinstance(right, datetime)
    ):
        return (
            _as_datetime(left),
            _as_datetime(right),
        )

    numeric = _numeric_pair(
        left,
        right,
    )

    if numeric is not None:
        return numeric

    if (
        isinstance(left, str)
        and isinstance(right, str)
    ):
        return (
            left.casefold(),
            right.casefold(),
        )

    if type(left) is not type(right):
        raise GovernedQueryError(
            "query comparison uses incompatible types"
        )

    return left, right


def _as_datetime(
    value: Any,
) -> datetime:
    if isinstance(
        value,
        datetime,
    ):
        parsed = value
    elif isinstance(
        value,
        str,
    ):
        clean = value.strip()
        if clean.endswith("Z"):
            clean = (
                clean[:-1]
                + "+00:00"
            )
        try:
            parsed = (
                datetime.fromisoformat(
                    clean
                )
            )
        except ValueError as error:
            raise GovernedQueryError(
                "query temporal value is not ISO-8601"
            ) from error
    else:
        raise GovernedQueryError(
            "query temporal comparison requires "
            "datetime or ISO-8601 string"
        )

    if parsed.tzinfo is None:
        parsed = parsed.replace(
            tzinfo=timezone.utc
        )

    return parsed.astimezone(
        timezone.utc
    )


def _numeric_pair(
    left: Any,
    right: Any,
):
    try:
        if isinstance(
            left,
            bool,
        ) or isinstance(
            right,
            bool,
        ):
            return None

        if not isinstance(
            left,
            (int, float, Decimal)
        ) or not isinstance(
            right,
            (int, float, Decimal)
        ):
            return None

        return (
            Decimal(str(left)),
            Decimal(str(right)),
        )
    except (
        InvalidOperation,
        ValueError,
    ):
        return None


def _aggregate_rows(
    *,
    rows,
    group_by,
    aggregates,
    now,
):
    grouped = {}

    if group_by:
        for row in rows:
            key = tuple(
                _resolve_expression(
                    item.expression,
                    row=row,
                    now=now,
                )
                for item in group_by
            )
            grouped.setdefault(
                key,
                [],
            ).append(row)
    else:
        grouped[()] = list(rows)

    output = []

    for key, members in grouped.items():
        result = {}

        for index, item in enumerate(
            group_by
        ):
            result[item.name] = (
                key[index]
            )

        for aggregate in aggregates:
            result[
                aggregate.name
            ] = _aggregate_value(
                aggregate,
                members=members,
                now=now,
            )

        output.append(
            result
        )

    return tuple(output)


def _aggregate_value(
    aggregate: QueryAggregate,
    *,
    members,
    now,
):
    if aggregate.operation == "count":
        return len(members)

    values = [
        _resolve_expression(
            aggregate.expression,
            row=row,
            now=now,
        )
        for row in members
    ]

    values = [
        value
        for value in values
        if value is not None
    ]

    if aggregate.operation == "count_distinct":
        return len({
            _hashable_value(value)
            for value in values
        })

    if not values:
        return None

    if aggregate.operation == "min":
        return min(values)

    if aggregate.operation == "max":
        return max(values)

    numeric = []

    for value in values:
        if (
            isinstance(value, bool)
            or not isinstance(
                value,
                (int, float, Decimal),
            )
        ):
            raise GovernedQueryError(
                "numeric aggregate received "
                "a non-numeric value"
            )

        numeric.append(
            Decimal(str(value))
        )

    total = sum(
        numeric,
        Decimal("0"),
    )

    if aggregate.operation == "sum":
        return _friendly_decimal(
            total
        )

    if aggregate.operation == "avg":
        return _friendly_decimal(
            total
            / Decimal(
                len(numeric)
            )
        )

    raise GovernedQueryError(
        "unknown aggregate operation"
    )


def _friendly_decimal(
    value: Decimal,
):
    integral = value.to_integral_value()

    if value == integral:
        return int(integral)

    return float(value)


def _hashable_value(
    value: Any,
):
    if isinstance(
        value,
        Mapping,
    ):
        return tuple(
            sorted(
                (
                    str(key),
                    _hashable_value(item),
                )
                for key, item in value.items()
            )
        )

    if isinstance(
        value,
        (list, tuple),
    ):
        return tuple(
            _hashable_value(item)
            for item in value
        )

    return value


def _order_rows(
    *,
    rows,
    order_by,
    raw_rows,
    now,
    aggregate_mode,
):
    del raw_rows
    del now
    del aggregate_mode

    ordered = list(rows)

    # Stable sorting from least-significant requested order to most significant
    # supports independent ascending/descending directions. Ordering is performed
    # only over values already present in the deterministic query output.
    for order in reversed(
        order_by
    ):
        ordered.sort(
            key=lambda item: _sortable_output_value(
                _output_order_value(
                    item,
                    order.expression,
                )
            ),
            reverse=(
                order.direction
                == "desc"
            ),
        )

    return tuple(ordered)


def _sortable_output_value(
    value: Any,
):
    # Keep missing values deterministic and sortable without inventing a value.
    if value is None:
        return (
            1,
            "",
        )

    if isinstance(
        value,
        bool,
    ):
        return (
            0,
            int(value),
        )

    if isinstance(
        value,
        (int, float, Decimal),
    ):
        return (
            0,
            Decimal(str(value)),
        )

    if isinstance(
        value,
        datetime,
    ):
        return (
            0,
            value,
        )

    return (
        0,
        str(value).casefold(),
    )

def _output_order_value(
    row: Mapping[str, Any],
    expression: QueryExpression,
):
    if isinstance(
        expression,
        QueryLiteral,
    ):
        return expression.value

    if isinstance(
        expression,
        QueryOutput,
    ):
        if expression.name not in row:
            raise GovernedQueryError(
                "order output reference is not available "
                "in query output"
            )
        return row[
            expression.name
        ]

    if isinstance(
        expression,
        QueryField,
    ):
        direct = (
            f"{expression.source}."
            f"{expression.fact}"
        )

        if direct in row:
            return row[direct]

        if expression.fact in row:
            return row[
                expression.fact
            ]

    raise GovernedQueryError(
        "order expression is not available "
        "in query output"
    )
